
### Create group
POST http://localhost:8000/api/v1/create_group
Content-Type: application/json

{
  "group_name": "group1"
}
###

### Create groups
POST http://localhost:8000/api/v1/create_groups
Content-Type: application/json

{
  "groups": [
    {
      "group_name": "group2",
      "size": 0
    },
    {
      "group_name": "group3",
      "size": 0
    },
    {
      "group_name": "group4",
      "size": 0
    }
  ]
}

POST http://localhost:8000/api/v1/create_student
Content-Type: application/json

{
  "first_name": "kim",
  "middle_name": "evgenevich",
  "last_name": "Arsinenko",
  "group_id": 1
}
###

### Create Student
POST http://localhost:8000/api/v1/create_teacher
Content-Type: application/json

{
  "first_name": "Ivan",
  "middle_name": "Ivanovich",
  "last_name": "Ivanov"
}

### Create Subject

POST http://localhost:8000/api/v1/create_subject

### Get Students

GET http://localhost:8000/api/v1/get_students

### Get groups

GET http://localhost:8000/api/v1/get_groups

### Get teachers
GET http://localhost:8000/api/v1/get_teachers

###

