
### Create group
POST http://localhost:8000/api/v1/create_group
Content-Type: application/json

{
  "group_name": "group1"
}
###

POST http://localhost:8000/api/v1/create_student
Content-Type: application/json

{
  "first_name": "kim",
  "middle_name": "evgenevich",
  "last_name": "Arsinenko",
  "group_id": 1
}
###

### Get Students

GET http://localhost:8000/api/v1/get_students

### Get groups

GET http://localhost:8000/api/v1/get_groups